In 8
UsersIT/inctagram pull request #2
Opened 2024-03-26 13:49 UTC by marinaDiubailo

Перенесла папку styles в слой app; подключила шрифт Inter как основной; создала семантические переменные.

2024-03-26 13:54 UTC, marinaDiubailo commented
run build production

2024-03-26 15:10 UTC, efValeron commented on src/app/styles/_typography.scss
> +  --font-weight-light: 300;
Нигде не используется, лучше удалить

2024-03-26 15:15 UTC, efValeron requested changes
Все хорошо, за исключением "_--font-weight-light: 300;_" -  **16 строка _typography.scss**
Строку желательно удалить

2024-03-26 15:27 UTC, efValeron approved these changes

2024-03-26 15:32 UTC, marinaDiubailo commented
run build production

2024-03-27 05:15 UTC, SukhanovPavel approved these changes

2024-03-27 06:16 UTC, marinaDiubailo commented
run build production

2024-03-27 06:25 UTC, merged

2024-03-27 06:26 UTC, marinaDiubailo commented
run build production