IN-17-Forgot-Password. feat: add forgotPassword page | add createNewPassword page
UsersIT/inctagram pull request #32
Opened 2024-05-29 03:59 UTC by SukhanovPavel

2024-05-29 04:02 UTC, SukhanovPavel commented
run build production

2024-05-31 03:36 UTC, SukhanovPavel commented
run build production

2024-05-31 05:15 UTC, marinaDiubailo commented
run build production

2024-06-05 05:34 UTC, SukhanovPavel commented
run build production

2024-06-05 05:40 UTC, SukhanovPavel commented
run build production

2024-06-05 05:57 UTC, SukhanovPavel commented
run build production

2024-06-05 06:00 UTC, SukhanovPavel commented
run build production

2024-06-06 05:52 UTC, SukhanovPavel commented
run build production

2024-06-06 20:57 UTC, SukhanovPavel commented
run build production

2024-07-31 08:13 UTC, marinaDiubailo commented
run build production

2024-07-31 08:41 UTC, marinaDiubailo requested changes

2024-07-31 08:41 UTC, marinaDiubailo commented on src/shared/ui/Controlled/ControlledTextField.tsx
Скажи, пожалуйста, почему поменял путь с относительного на абсолютный? Мне просто любопытно)

2024-07-31 08:41 UTC, marinaDiubailo commented on src/pages/create-new-password/ui/CreateNewPassword.tsx
Мое мнение: useRecoveryCodeCheckMutation тоже стоит добавить в паблик апи @/src/features/auth)

2024-07-31 17:00 UTC, Yuri-dot-com commented on src/shared/ui/Controlled/ControlledTextField.tsx
Вообще не помню что бы в этом файлике что либо трогал(

2024-07-31 17:01 UTC, Yuri-dot-com commented on src/pages/create-new-password/ui/CreateNewPassword.tsx
Да, можно

2024-07-31 17:29 UTC, Yuri-dot-com commented on src/pages/create-new-password/ui/CreateNewPassword.tsx
покопался нашел, это пришло с коммитом когда я первый раз вмерджил dev в ветку с фичей

2024-07-31 17:30 UTC, Yuri-dot-com commented on src/shared/ui/Controlled/ControlledTextField.tsx
покопался нашел, это пришло с коммитом когда я первый раз вмерджил dev в ветку с фичей. Т/е пришло ко мне из Dev

2024-07-31 18:20 UTC, marinaDiubailo commented on src/shared/ui/Controlled/ControlledTextField.tsx
Аааа, понятненько)) Я о таком и не подумала.

2024-07-31 18:20 UTC, marinaDiubailo approved these changes

2024-07-31 18:21 UTC, marinaDiubailo commented on src/pages/create-new-password/ui/CreateNewPassword.tsx
Спасибо, что пофиксил)

2024-07-31 18:21 UTC, marinaDiubailo commented
run build production

2024-08-01 12:28 UTC, Halina2610 approved these changes

2024-08-01 16:38 UTC, merged