In image uploader, Avatar, TextArea
UsersIT/inctagram pull request #36
Opened 2024-06-16 11:26 UTC by Halina2610

Added components: Avatar (native), Text-Area (native), Image Uploader Input (native), and Image Uploader. These components are reusable, and the schema (ImageSchema) is also reusable.

2024-06-17 07:12 UTC, marinaDiubailo commented
run build production

2024-06-17 19:46 UTC, Halina2610 commented
run build production

2024-06-18 07:38 UTC, marinaDiubailo commented
run build production

2024-06-18 07:47 UTC, marinaDiubailo approved these changes

2024-06-18 08:32 UTC, efValeron requested changes
## Исправления Textarea

Textarea по стилям **должна** быть похожа на Input!

1. **Стилизация**:
      - Отсутствуют плавные анимации.
      - **Placeholder**: Не должен быть белым.
      - **Граница**: При нажатии граница не должна становиться белой.

2. **Отображение количества символов**:
    - Думаю стоит добавить отображение количества символов. 
    - В props передавать максимальное количество символов.
    - Ссылка на макет в Figma: [макет](https://www.figma.com/design/M7753HAzy0tm9rQWyRBrnI/Inctagram?node-id=309-6266&t=f8fr7j2tx2BZLW2l-4)

2024-06-18 14:27 UTC, Halina2610 commented
run build production

2024-06-18 14:28 UTC, Halina2610 commented
run build production

2024-06-18 14:28 UTC, Halina2610 commented
run build production

2024-06-18 17:34 UTC, Halina2610 commented
run build production

2024-06-18 18:48 UTC, marinaDiubailo commented
run build production

2024-06-18 18:52 UTC, Halina2610 commented
run build production

2024-06-19 05:42 UTC, efValeron approved these changes

2024-06-19 13:17 UTC, merged