In 33 date picker
UsersIT/inctagram pull request #39
Opened 2024-06-30 21:30 UTC by Halina2610

2024-06-30 21:30 UTC, Halina2610 commented
run build production

2024-06-30 21:35 UTC, Halina2610 commented
Стили дата-пикера изменены, не совпадают с [figma](https://www.figma.com/design/M7753HAzy0tm9rQWyRBrnI/Inctagram?node-id=1-12&t=w7nP2skCAlTDqDVX-0)
Переменная для отображения ошибки, если юзеру менее13 лет 
`  const minAge = new Date().setFullYear(new Date().getFullYear() - 13)
  const defaultValue = data ? new Date(data) : new Date(minAge)`

2024-06-30 21:35 UTC, Halina2610 commented
run build production

2024-06-30 21:43 UTC, Halina2610 commented
run build production

2024-06-30 21:51 UTC, Halina2610 commented
run build production

2024-07-01 07:54 UTC, marinaDiubailo approved these changes

2024-07-02 08:02 UTC, efValeron requested changes

2024-07-02 08:02 UTC, efValeron commented on src/shared/ui/DatePicker/DatePickerInput.module.scss
> +  :global(.rmdp-header-values) {
Этот hover лучше заменить на примерно такой код:
```tsx
:global(.rmdp-header-values) {
  display: flex;
  align-items: center;
  height: 32px;
  
  > :hover {
    color: var(--color-accent-900) !important;
    transition: all 0.2s;
  }
}
```
Потому что, когда я навожу на год, меняет цвет и год и месяц:

<img src="https://github.com/UsersIT/inctagram/assets/72882255/6936da28-77db-41ba-8412-cf9be58fe33e"  width="30%" height="30%">

Результат такой:

<img src="https://github.com/UsersIT/inctagram/assets/72882255/85975949-47ec-492d-9f4c-e21136a18f6e"  width="30%" height="30%">

2024-07-02 08:54 UTC, efValeron commented on src/shared/locales/ru.ts
> +    errorAge: 'Пользователь младше 13 лет не может создать профиль.',
Зачем два одинаковых поля `calendar` и `errorAge`
Будет лучше сообщение о 13 лет добавть не в `errors` а в `validation`

2024-07-02 08:55 UTC, efValeron commented on src/shared/locales/ru.ts
> +    errorAge: 'Пользователь младше 13 лет не может создать профиль.',
Зачем два одинаковых поля `calendar` и `errorAge`
Будет лучше сообщение о 13 лет добавть не в `errors` а в `validation`

2024-07-02 08:55 UTC, efValeron commented on src/shared/locales/en.ts
> +    errorAge: 'A user under 13 cannot create profile',
Зачем два одинаковых поля `calendar` и `errorAge`
Будет лучше сообщение о 13 лет добавть не в `errors` а в `validation`

2024-07-02 09:20 UTC, efValeron commented on src/shared/ui/DatePicker/DatePickerInput.tsx
> +  defaultValue: Date | null
Возможно лучше сделать это поле необязательным:
```suggestion
  defaultValue?: Date | null
```

Ибо ControlledDatePicker требует передать атрибут defaultValue, но когда я передаю он ругается типом.
Передаю я в него `new Date()` или `null`, но результат один:

![image](https://github.com/UsersIT/inctagram/assets/72882255/0cb8d47e-949a-4edc-b8b8-d3bafdd05564)
![image](https://github.com/UsersIT/inctagram/assets/72882255/fdac83d9-37ea-4339-983a-7be960e7ecaf)

Но как бы `defaultValue` то работает, то есть если передать `new Date('2022-01-01')`, то все гуд. Но вот тип ругается.

Так же я не могу поставить значение по умолчанию через `useForm`, оно буквально ничего не делает:

![image](https://github.com/UsersIT/inctagram/assets/72882255/273d0f56-7b67-4404-b0fe-cb8dda9ddb47)

2024-07-02 09:29 UTC, efValeron commented
Также я заметил, что не могу изменить длинну инпута, ни через классы не через атрибут `style`.
Получается что он всегда в 100% длинну, а это не всегда может быть так

2024-07-02 09:30 UTC, efValeron reviewed
Также я заметил, что не могу изменить длинну инпута, ни через классы не через атрибут style.
Получается что он всегда в 100% длинну, а это не всегда может быть так.

2024-07-02 16:37 UTC, Halina2610 commented on src/shared/ui/DatePicker/DatePickerInput.module.scss
> +  :global(.rmdp-header-values) {
Это подправила

2024-07-02 16:38 UTC, Halina2610 commented on src/shared/locales/ru.ts
> +    errorAge: 'Пользователь младше 13 лет не может создать профиль.',
+

2024-07-02 16:41 UTC, Halina2610 commented on src/shared/locales/en.ts
> +    errorAge: 'A user under 13 cannot create profile',
Исправила

2024-07-02 18:06 UTC, Halina2610 commented on src/shared/ui/DatePicker/DatePickerInput.tsx
> +  defaultValue: Date | null
Подправила. Но что бы передать дату ее нужно преобразовать к одному из типа Values. К примеру ` defaultValue={new Date('2022-01-01').toString()}`

2024-07-02 18:15 UTC, Halina2610 commented on src/shared/ui/DatePicker/DatePickerInput.tsx
> +  defaultValue: Date | null
type Value = Date | string | number | DateObject | null; Если передавать Date то непонятно почему ругается на типы, передаешь число или строку все нормально

2024-07-02 18:39 UTC, Halina2610 commented
run build production

2024-07-04 06:33 UTC, efValeron requested changes

2024-07-04 06:33 UTC, efValeron commented on src/shared/locales/en.ts
> +    validAge: 'A user under 13 cannot create profile',
Я думаю лучше назвать что то типо ageRestriction

2024-07-04 06:33 UTC, efValeron commented on src/shared/locales/ru.ts
> +    validAge: 'Пользователь младше 13 лет не может создать профиль.',
Я думаю лучше назвать что то типо ageRestriction

2024-07-04 16:12 UTC, Halina2610 commented on src/shared/locales/ru.ts
> +    validAge: 'Пользователь младше 13 лет не может создать профиль.',
ок

2024-07-05 13:59 UTC, efValeron approved these changes

2024-07-05 14:00 UTC, efValeron commented
run build production

2024-07-05 17:08 UTC, Halina2610 commented
run build production

2024-07-05 17:09 UTC, merged