IN-56 Paid Account
UsersIT/inctagram pull request #65
Opened 2024-10-11 12:53 UTC by efValeron

2024-10-11 12:53 UTC, efValeron commented
run build production

2024-10-11 13:33 UTC, marinaDiubailo requested changes

2024-10-11 13:33 UTC, marinaDiubailo commented on src/features/subscribeToBusinessAccount/ui/SubscriptionSelectionSection/SubscriptionSelectionSection.tsx
Пропиши, пожалуйста, относительные пути для импортов из соседних папок:
Например: import { useSubscribeMutation } from '../../api/subscribeApi' вместо import { useSubscribeMutation } from '@/src/features/subscribeToBusinessAccount/api/subscribeApi'
+ иконки у нас все в shared/assets а импорт в слой features из pages это нарушение fsd.

2024-10-11 13:33 UTC, marinaDiubailo commented on src/features/subscribeToBusinessAccount/ui/SubscriptionSelectionSection/SubscriptionSelectionSection.tsx
import { PayPalIcon } from '@/src/pages/profile/ui/SettingsAccountManagmentTab/PayPalIcon'
import { StripeIcon } from '@/src/pages/profile/ui/SettingsAccountManagmentTab/StripeIcon'
я про этот момент

2024-10-12 18:43 UTC, Halina2610 approved these changes

2024-10-14 13:36 UTC, efValeron commented
run build production

2024-10-15 08:10 UTC, marinaDiubailo approved these changes

2024-10-17 08:03 UTC, merged