In 45 editing a post
UsersIT/inctagram pull request #77
Opened 2024-11-04 07:54 UTC by Halina2610

2024-11-04 07:54 UTC, Halina2610 commented
Добавлена возможность редактирования поста. Есть проблема в том, что если пост создан сразу после перехода на страницу пользователя, postList не обновляется, эта же проблема и с редактированием поста. Если профиль открыт некоторое время и пользователь создает или редактирует профиль, eventEmitter работает, но таким образом.

В мобильной версии редактора отошла от дизайна, из-за модального окна.

Реализована логика добавления комментария, однако без ТЗ требования не понятны, сделала для визуализации общей картинки, в мобильной версии не реализовывала.

2024-11-07 08:50 UTC, marinaDiubailo requested changes

2024-11-07 08:50 UTC, marinaDiubailo commented on src/entities/comment/ui/CommentCard/CommentCard.tsx
import { Heart } from '@/src/shared/assets/icons'
вроде лишний импорт.

2024-11-07 08:50 UTC, marinaDiubailo commented on src/widgets/post-modal/api/userPostApi.ts
url: `v1/posts/${postId}/comments`,
добавь, пожалуйста в apiEndpoints.
const params = new URLSearchParams()

        if (pageSize) {
          params.append('pageSize', pageSize.toString())
        }
        if (pageNumber) {
          params.append('pageNumber', pageNumber.toString())
        }
        if (sortBy) {
          params.append('sortBy', sortBy)
        }
        if (sortDirection) {
          params.append('sortDirection', sortDirection)
        }

        return {
          method: 'GET', метод 'GET' по умолчанию, так что его можно не писать
          url: `${apiEndpoints.posts.posts}/${postId}/comments?${params.toString()}`,
         params: { квери параметры можно сюда добавлять без использования new URLSearchParams() + pageSize,  sortBy, sortDirection можно задать по умолчанию, чтобы не делать этого в компоненте}
        }
        Например, вот такой вариант для сокращения строк кода:
        getComments: builder.query<GetCommentsResponse, GetCommentsParams>({
      query: ({ pageNumber, pageSize = 10, postId, sortBy = 'createdAt', sortDirection ='desc' }) => {
               return {
          url: `${apiEndpoints.posts.posts}/${postId}/comments`,
          params: { pageNumber, pageSize, sortBy, sortDirection }
        }
      },
    }),

2024-11-07 08:50 UTC, marinaDiubailo commented on src/widgets/post-modal/api/userPostApi.ts
import { GetUserPostsResponse } from '@/src/features/posts/model/types/api' нужно добавить в паблик апи
import {
  ...
} from '@/src/widgets/post-modal/model/types/api' импорт внутри слайса должен быть относительным)))

2024-11-07 08:50 UTC, marinaDiubailo commented on src/widgets/post-modal/index.ts
export { PostModal } from './ui/PostModal/PostModal'

2024-11-07 08:50 UTC, marinaDiubailo commented on src/widgets/post-modal/model/schemas/addCommentValidationSchema.ts
import { LocaleType } from '@/src/shared/locales/ru'

import { z } from 'zod'

export const addCommentValidationSchema = (t: LocaleType) =>
  z.object({
    comment: z.string().min(1, t.errors.required).max(300, t.errors.maxLength),
  })

export type AddCommentFormValues = z.infer<ReturnType<typeof addCommentValidationSchema>>

2024-11-07 08:50 UTC, marinaDiubailo commented on src/widgets/post-modal/model/types/api.ts
import { GetAllPublicPostsArgs, ImageType } from '@/src/features/posts/model/types/api'
подправь, пожалуйста, на правильный импорт из публичного апи

2024-11-07 08:50 UTC, marinaDiubailo commented on src/widgets/public-post-modal/ui/PostComments/PostComments.tsx
role={'list-item'} вообще, вроде как роль должна быть написана без дефиса, но здесь я ее, в принципе, зря добавляла, так как и для ul роль list по умолчанию, и для li роль listitem тоже по умолчанию, поэтому их можно вообще удалить. Я может сама потом исправлю, так как это я их там прописала)

2024-11-08 08:17 UTC, marinaDiubailo approved these changes

2024-11-08 09:15 UTC, efValeron approved these changes

2024-11-08 20:05 UTC, merged